# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    tags:
      - 'v*'  # This pattern matches tags that start with 'v', e.g., v1.0.0

jobs:

  npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14

      - name: Build with Emscripten
        run: |
          emcmake cmake -B build -DWASM=true -DCLI=false -DTEST=false -DCURL=false -DCMAKE_BUILD_TYPE=MINSIZREL -S .
          cmake --build build

      - name: Set package version from tag
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          echo "Setting version to $TAG_VERSION in package.json"
          npm version $TAG_VERSION --no-git-tag-version
        working-directory: build/emscripten
  
      - name: Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          cp ../../README.md .
          cp ../../LICENSE .
          cp ../../c4_logo.png .
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: build/emscripten
permissions:
  contents: read
  checks: write
  pull-requests: write
  actions: read